server:
  port: 8081

spring:
  cloud:
    stream:
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'tcp://localhost:55556'
                msgVpn: default
                clientUsername: default
                clientPassword: default
logging:
  level:
    root: info
    com:
      solacesystems: warn
      solace: warn
    org:
      apache: warn
      springframework: warn
  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr([%thread]) %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
